### ISSUE TITLE
Long option input values can overflow the field

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#10]
Some of the longest text options can overflow the default width of the input field.
Example: Luci statistics / collectd / output plugins / RRDtool:
![textoverflow](https://cloud.githubusercontent.com/assets/7926856/10122850/e4e975d6-652f-11e5-9669-a81d1a775a06.PNG)
(that is the default value for that option, so nothing imaginary or special. But might still be one of the longest default values: "1hour 1day 1week 1month 1year")

I tested both with IE11 and Firefox43, and the same result.

It would be better if the input field would adjust to long input values, if necessary. At least if the value is long already when the page is first rendered.

**Comment by LuttyYang** [comment]
I fix it in version 0.2.5

**Comment by hnyman** [comment]
Thanks
