### ISSUE TITLE
Multiselection box gets rendered wrong in Luci statistics / Interface plugin config

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#11]
The interface selection box in the Luci statistics config of the Interface plugin gets rendered wrong in Material. (Note: you need to have installed luci-app-statistics to see that.)

EDIT: I changed the title as I realized that it is not a dropdown, but a multiselection box, where you can select several values.

Material:
====
![interface_material](https://cloud.githubusercontent.com/assets/7926856/10122923/95fedd88-6531-11e5-926e-ca6ad4f486f9.PNG)

Bootstrap:
====
![interface_bootstrap](https://cloud.githubusercontent.com/assets/7926856/10122917/8d4bd6d2-6531-11e5-84ab-f4e0cd737726.PNG)

**Comment by LuttyYang** [comment]
I fix it in version 0.2.5

**Comment by hnyman** [comment]
Thanks
