### ISSUE TITLE
Mouse-hover indicator for the horizontal menu causes flickering

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#12]
Looks like there is no space reserved for the mouse-hover indicator in the horizontal menu. That causes some vertical flickering when mouse moves to hover over an menu item. The page below moves a few pixels down when the indicator gets created and back up hwn mouse moves away. That looks like flickering :-(

The below image shows how the page contents have been pushed down by the indicator. The left side shows the normal placement and the right side shows the placement when indicator is visible.
![mousehover](https://cloud.githubusercontent.com/assets/7926856/10123171/27227d70-653b-11e5-9d46-08c68e5af8d3.PNG)

**Comment by LuttyYang** [comment]
I fix it in version 0.2.5

**Comment by hnyman** [comment]
Thanks.

**Comment by LuttyYang** [comment]
not at all

**Comment by hnyman** [comment]
I installed manually your "0.25" to test it, but it would be good to import the changes to the sources in the Openwrt Luci repo, so that users will get the changes to their own personal builds and the changes are included in the daily buildbot snapshots. Hopefully you will create a pull request in the near future.

**Comment by hnyman** [comment]
@LuttyYang 
Could you please create a pull request to uplift the changes in 0.25 to the Openwrt Luci repository.
Or should I cherrypick your changes to the repo?

**Comment by LuttyYang** [comment]
Sorry, over the past few days I am very busy

**Comment by LuttyYang** [comment]
After a few hours I would probably create a pull request

**Comment by hnyman** [comment]
Sounds good ;-)

**Comment by LuttyYang** [comment]
@hnyman  I created a pull request.
