### ISSUE TITLE
Some screens do not fit well to narrower screens than 1920 pixels

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#13]
Material theme mainly scales well, but some screens contain so many items that they do not scale well due to the theme's preference to large buttons and large text. Material is probably targeting tablet users, for whom a physically small but 1920-pixel-wide screen is typical and large fotn size makes sense. But with 24-inch or larger monitors in desktop use, you rarely browse with full width window. (At least I do not...) Material prefers rather large text to the input fields, which is unnecessary with a large monitor screen.

One example of a problematic core page is "firewall" config. With a screen less than 1920 pixels, the items never fit to the  visible page. The page items do not scale, but overflow the right side. 
Below is comparison between Bootstrap and Material. In material the "zone boxes" take quite much horizontal space and also the enable/disable selection boxes do that:
![firewall_wide](https://cloud.githubusercontent.com/assets/7926856/10134413/42c27ea0-65ee-11e5-9776-8c01f6e3ced4.PNG)

I am not sure if you can do anything the improve things for desktop users (somehow adjust to the physical size of the screen?), but I wanted to highlight the issue in any case.

**Comment by Ranger-Z** [comment]
I think the scale makes it great on a cell phone, First GUI I can see on my phone

**Comment by LuttyYang** [comment]
@hnyman I adjusted the some size. Is it much better now?

**Comment by hnyman** [comment]
I applied manually your patches and it seems a bit better now. It is still wide, but not quite 1920 px. Maybe 1650 px now. The zone boxes (wan, wan6 ...) look better.

![fw_wide2](https://cloud.githubusercontent.com/assets/7926856/10335845/ac44fbb8-6cfc-11e5-8c2d-3024180b3a81.PNG)

The theme design makes it probably hard to decrease size much more, so I am not sure how much effort you should spend on this. 

But one possible idea for you: could the zone boxes (interfaces included in a zone: wan, wan6, sixxs, ...) be arranged vertically inside the box instead of horizontal? I haven't checked the Luci source, if the placement comes from the source, but if that can be arranged in style, that could decrease the horizontal space.


Ps. One additional notion: was it really intentional to hardcode 0.2.9 version to header.htm and footer.htm in commit https://github.com/LuttyYang/luci-theme-material/commit/74c23134a633b1ff38e3aa50628972b2934cbe5c ?  
It still says 0.2.9 there, also in the 0.2.10 release... Earlier there was no version specification.

**Comment by LuttyYang** [comment]
@hnyman Ohhhh... Is there any other automated way to solve this problem?

**Comment by hnyman** [comment]
Sorry, I am not sure to which problem you refer. (the firewall screen or the probably accidental 0.2.9 spec in https://github.com/LuttyYang/luci-theme-material/blob/master/files/templates/footer.htm#L45 and header.htm)

**Comment by LuttyYang** [comment]
@hnyman 
How to automatically add the current version number to header.htm and footer.htm files.

thanks

**Comment by hnyman** [comment]
Ahh, that question.

On the Openwrt side there is no need to set a version number for the theme, as the luci package version number gets automatically created from the date, time and hash of the last commit in the Luci repo: https://github.com/openwrt/luci/blob/master/luci.mk#L52
e.g. "git-15.278.60928-3289e13"
(logic explained in https://github.com/openwrt/luci/commit/0856030c79f3febdafa627511cf1be4c72edf09b )

That variable is set during the make process and is then used for all the components. There is usually no separate revision IDs for components like modules, applications or themes.

When the buildbot builds the packages automatically every 1-2 days, the version gets set each time according to that last commit. The same also happens if somebody builds his own firmware including the theme. The version is the date/time/hash based one.

Regarding your own 0.2.9 and 0.2.10 etc. builds published at your own site, I do not know any better way to do it. The PKG_VERSION that you define in the Makefile should get applied, I think. But the end-users will probably still see the main luci version in the footer.

In general, I think that most users will either download the most recent theme from the snapshot repo (e.g. https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/luci/ ) as firmware's opkg will fetch it from there or alternatively they include the theme in their build (using luci feed from github/luci). I don't believe that many people will directly download the 0.2.9 etc. revisions from your site. I may be wrong, but that is my hunch.

**Comment by LuttyYang** [comment]
@hnyman I think you misunderstood my point. I just to prevent caching problems...

**Comment by hnyman** [comment]
Yeah, I got your purpose wrong.

Would it be possible to include the version variable in a similar fashion as the hard-coded version string? (not say absolute 0.2.9 there, but instead reference to the variable's value, which would be) 

Line on line #31 the ver.luciversion is used:
https://github.com/LuttyYang/luci-theme-material/blob/master/files/templates/footer.htm#L31

    <a href="https://github.com/openwrt/luci">Powered by <%= ver.luciname %> (<%= ver.luciversion %>)</a> /

If similar things works, that would force the cache to refresh at least when a new Luci version gets installed.

**Comment by LuttyYang** [comment]
@hnyman OK, thank you very much.

**Comment by hnyman** [comment]
I compiled the material theme after your PR https://github.com/openwrt/luci/pull/513 with 0.2.11 and noticed something negative:

I think that the idea of forcing the browser to update style.css and script.js after the theme is updated, is ok on principle, but the effect of the changes in https://github.com/openwrt/luci/pull/513 make style.css and scripts.js to never cache (at least in Firefox). They are always reloaded from the server, for each Luci page refresh (as the link contains the query element "?git...").

![capture0211first](https://cloud.githubusercontent.com/assets/7926856/10460615/bd1bc77e-71dd-11e5-983d-58f749d182bd.PNG)

That was probably not quite the intention. It overshoots the purpose of forcing an update for the theme.

From performance perspective, loading these style files again and again for each page is unnecessary. I am not sure if forcing the cache-refresh is really needed. It might be better to revert to the original situation, where it is up to the user to force a cache cleanup / style reload, if he notices something rendering wrongly.

**Comment by LuttyYang** [comment]
I fix it in version 0.2.13

**Comment by hnyman** [comment]
I return to the screen width / text size issue:

After the most recent fixes (menu system etc.), I see much too small text for the detail items on two pages:
network / firewall
network / switch

Below are two images from Firefox and one from IE11, where the text is even smaller...

Everything fits now to the screen, but is rather unusable on those two screens :-(

![textsizefirewallzones](https://cloud.githubusercontent.com/assets/7926856/10699030/ab7f3a64-79bc-11e5-9aa9-eb6e000c0f60.png)

![textsizeswitch](https://cloud.githubusercontent.com/assets/7926856/10699036/aed878e2-79bc-11e5-86f3-4aae6df664d3.png)

![ietextsizefirewallzones](https://cloud.githubusercontent.com/assets/7926856/10699077/e89fe5ce-79bc-11e5-835a-7a3a00ad2110.png)

**Comment by LuttyYang** [comment]
Okey...

**Comment by LuttyYang** [comment]
@hnyman I fix it in version 0.2.15

**Comment by hnyman** [comment]
Thanks, looks better now.
