### ISSUE TITLE
List of available software items does not word-wrap

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#14]
The description field of the available software packages does not word-wrap (like it does in Bootstrap). That decreases usability, as some of the packages have really long explanatory descriptions.

Steps to reproduce:
 * update opkg package list (either in Luci "Update lists" in System/Software page or "opkg update" in console)
 * go in Luci to System / Software page --> "Available packages" tab 

Screenshot below:
![software_description](https://cloud.githubusercontent.com/assets/7926856/10142148/93d3e812-6619-11e5-8a80-2ce44ae5e350.PNG)

**Comment by LuttyYang** [comment]
@hnyman maybe i fix it in version 0.2.6

**Comment by hnyman** [comment]
Sorry, but after compiling and flashing the version at Openwrt Luci after your pull request (matches 0.26, I think) I still see no word-wrapping there.

**Comment by LuttyYang** [comment]
Could you tell me that you are using environmental information it?

E.g:
System: Ubuntu 15.04
Browser: Firefox dev 38.0.1

**Comment by hnyman** [comment]
I mainly use Firefox 43 x64 in Window 7 x64
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0 
ID:20151005004046 CSet: 58f5e8ddaa59b31dec9938a83cc24210cb514896

also IE11, standard version.
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

And the word-wrap does not work in either. Instead, the description field is one long line.
 
Firefox 43:
![software_overflow_right](https://cloud.githubusercontent.com/assets/7926856/10303270/22a8f3aa-6c1b-11e5-8369-a267faa70372.PNG)

IE11:
![overflow_ie11](https://cloud.githubusercontent.com/assets/7926856/10303274/246754ac-6c1b-11e5-8d70-2504431cc855.PNG)

**Comment by LuttyYang** [comment]
@hnyman I test IE11, but it look like good...

![image](https://cloud.githubusercontent.com/assets/14296262/10303406/0d67e6ba-6c46-11e5-985e-8a50a6775126.png)

![image](https://cloud.githubusercontent.com/assets/14296262/10303368/e4115300-6c45-11e5-943f-4a49509dc0f1.png)

**Comment by hnyman** [comment]
Hmmm. interesting.
I am testing with the version uplifted to Openwrt repository with the pull request yesterday, not the local 0.26. Is there a difference?

I thought about cache problems and also tested in Virtualbox Ubuntu with a virgin Firefox 41, and no wrap.
![ubuntufirefox41](https://cloud.githubusercontent.com/assets/7926856/10303517/e82eea16-6c1c-11e5-85e1-f1b0158ab3a7.PNG)

**Comment by LuttyYang** [comment]
@hnyman I compared the https://github.com/LuttyYang/luci-theme-material/blob/master/files/htdocs/css/style.css and https://github.com/openwrt/luci/blob/master/themes/luci-theme-material/htdocs/luci-static/material/css/style.css.

They look the same....

**Comment by LuttyYang** [comment]
![screenshot from 2015-10-06 16 25 00](https://cloud.githubusercontent.com/assets/14296262/10303825/fdde0a1e-6c48-11e5-9bf3-17c8afaa0d94.png)

 I tested FireFox, it also look like good...

I think maybe the javaScript have some problems. Could you take a screenshot of this page? you need press F12 in this page, it look like this:
![image](https://cloud.githubusercontent.com/assets/14296262/10303989/e642706a-6c49-11e5-98c4-e31d7c45c904.png)

**Comment by hnyman** [comment]
I also tested with Chrome from my tablet and no wrap.

I just recompiled and flashed a new version to the router, but no change.

You mean this screen?
![capture2](https://cloud.githubusercontent.com/assets/7926856/10304175/3166ddde-6c21-11e5-8571-82d3446372f5.PNG)

**Comment by hnyman** [comment]
Just making sure that we are talking about the same version:

which change in 0.26 was supposed to cause the wrapping?
https://github.com/LuttyYang/luci-theme-material/commit/7cce322770ac3ff300ba9f5e1fbc1e96764a4e82

or has it been wrapping ok for you all the time?

**Comment by hnyman** [comment]
one more screenshot, with moer drilling down to the table item level:
If I understand the pop-up item info ok, the field is 4990 pixels wide.

![drilldown](https://cloud.githubusercontent.com/assets/7926856/10304898/998c9594-6c25-11e5-8f09-32cf4e654e85.png)

**Comment by LuttyYang** [comment]
@hnyman 

![image](https://cloud.githubusercontent.com/assets/14296262/10305021/3bf9450a-6c50-11e5-9054-60785790693b.png)

**Comment by LuttyYang** [comment]
I thought it maybe the LUCI Template have some change?

**Comment by hnyman** [comment]
You are not using the newest Openwrt trunk version, as your software page has no package  size information.

**Comment by LuttyYang** [comment]
@hnyman Okay... It seems that I need build a newest version for my router ...

**Comment by hnyman** [comment]
Yeah, it looks like you are not using the newest Luci code , as your software page has no package  size information. opkg size that was added to Luci on September 16th by https://github.com/openwrt/luci/commit/3288fe76ab3d2269abcf902d0df6f847c6200e8e

You need to sync your sources.

**Comment by hnyman** [comment]
Just tested: after manually changing style.css to affect 5th column instead of 4th, the description column started to wrap. So, the style in 0.26 is based on older luci code.

Looks like the styling is so detailed that it may cause additional work when there are changes in Luci. Is the a fundamental reason, why all the columns are not wrapping in this table? That might ease things in future. 

Luci evolves all the time, so the more flexible the styling is, the better it works automatically.
(some historical background: the package version string shown in this table was up to ~55 characters still a few feeks ago. Then its display was shortened to max 26 chars, decreasing the need to wrap that column. But earlier that field got often wrapped, too. There are constantly minor tweaks, so the detailed formatting may prove to be burdensome at some point.)

screenshot about the working 5th column wrapping
![stylecss_change](https://cloud.githubusercontent.com/assets/7926856/10307307/87fbe8aa-6c36-11e5-86fb-c543c772f4fe.PNG)

**Comment by LuttyYang** [comment]
@hnyman I also thinking this problem, LUCI Template have many old HTML, example, all button used input(style is button) as opposed to use button. It is difficult to change one style without affecting the others.

**Comment by LuttyYang** [comment]
@hnyman I fix it in version 0.2.7, and I create a PR for this version.

**Comment by hnyman** [comment]
Thanks. I merged the PR and now it seems to wrap ok.
