### ISSUE TITLE
Code change in header.htm

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#15]
You are probably monitoring the changes in the Openwrt Luci repo, but I am still highlighting that there was yesterday a change to themes' header.htm files by Jow, also to the one in the material theme.

https://github.com/openwrt/luci/commit/36f133f946f1118fca9004706b8f2c2a741fd006

(General context: crsf token and form action handling. See https://github.com/openwrt/luci/commits/master )

You need to repeat that change in your local repo, or otherwise the your compiled versions 0.28+ start losing some functionality.

Change history for luci-theme-material directory at Luci repo: https://github.com/openwrt/luci/commits/master/themes/luci-theme-material

I am not quite sure what is the easiest way to backport this kind of fixes. It might be merging the upstream repo to here, or it might be by downloading the possible few commits as patches and applying them locally (as Github offers a nice way to download a commit as patch just by adding .patch to the end of the commit link: https://github.com/openwrt/luci/commit/36f133f946f1118fca9004706b8f2c2a741fd006.patch ).

**Comment by LuttyYang** [comment]
@hnyman Thank you informed me about this, I already synchronize for header.htm.

**Comment by hnyman** [comment]
You should maybe create the next pull request, as most users will get the source/package from the  Openwrt Luci repo / snapshots, which are current based on your 0.2.7 as that was the base for https://github.com/openwrt/luci/pull/503

**Comment by LuttyYang** [comment]
ok, I will

Thanks.
