### ISSUE TITLE
Version Upgrade Process

### ISSUE THREAD

**Issue by Ranger-Z** [LuttyYang/luci-theme-material#16]
Simple question, what is the proper way to upgrade?  I have been changing the theme to bootstrap, removing the old package, installing the new, changing back the theme.

Do I need to do this, or can I just install the replacement package?

**Comment by LuttyYang** [comment]
You can switch themes in System - System - Language and Style - Design

When you upgrade the theme you can just install the replacement package.

Thanks

**Comment by Ranger-Z** [comment]
Lutty, You can close this, but can you please reopen #8, or do I need to start a new issue?
