### ISSUE TITLE
Layout glitches

### ISSUE THREAD

**Issue by obsy** [LuttyYang/luci-theme-material#2]
![screenshot-192 168 1 1 2015-09-17 17-56-44](https://cloud.githubusercontent.com/assets/695356/9938447/b0c079f2-5d65-11e5-8b25-d7e1b5cb2c45.png)

On login page, if language set on "Auto" or "Polish". English is ok.

![screenshot-192 168 1 1 2015-09-17 17-57-41](https://cloud.githubusercontent.com/assets/695356/9938487/d98e843c-5d65-11e5-93c5-777fc05af2e1.png)

And logout is   other type.

**Comment by LuttyYang** [comment]
I did not fully understand what you mean.

If you change language, you need refresh the page to take it effective

**Comment by obsy** [comment]
Yes, page is refreshed. Input field is not aligned to left

**Comment by hnyman** [comment]
I will add  a few observations to the same issue:

1)
Like obsy said, the "logout" text looks different. Maybe intentionally, but still.
The underlining makes the font look smaller?
The Logout font is the same size as the sub-level menu items?
![logoutfont](https://cloud.githubusercontent.com/assets/7926856/9945377/965609f8-5d95-11e5-99b5-65a4a6a66769.PNG)

2)
Other issue is the notification about the "unsaved changes" after you have done config changes, pressed "save", but not yet "save and apply". Bootstrap shows the notification better than Material.

Material:
![unsavedchanges_material](https://cloud.githubusercontent.com/assets/7926856/9945410/c65e3bde-5d95-11e5-9bf5-6f12d7c4a69d.PNG)

Bootstrap:
![unsavedchanges_bootstrap](https://cloud.githubusercontent.com/assets/7926856/9945415/cac675c4-5d95-11e5-9821-fb411090e218.PNG)

**Comment by LuttyYang** [comment]
@obsy  @hnyman  i fixed "logout" theme on version 0.1.2

@hnyman  i fixed "unsaved changes" theme and  "unsaved changes" mobile page dislocation on version 0.1.2

![image](https://cloud.githubusercontent.com/assets/14296262/9951385/67a4a430-5df8-11e5-94af-095444190e6a.png)

@obsy In login page Polish text longer than English text, I overlooked that aspect. I will fix it on a later version

**Comment by obsy** [comment]
Or I can just change text to shorter version. ("Nazwa użytkownika" -> "Login").

**Comment by LuttyYang** [comment]
@obsy I fix Polish text longer bug on version 0.1.3

![image](https://cloud.githubusercontent.com/assets/14296262/9952846/1ffb0ee8-5e0d-11e5-858d-809b794d1178.png)

**Comment by hnyman** [comment]
Tested with your 1.3 and it looks better.
