### ISSUE TITLE
Would you please release an available version for Barrier Breaker?

### ISSUE THREAD

**Issue by angusding** [LuttyYang/luci-theme-material#20]
I can build 0.2.15 to BB version, but can't apply. That's the error information about BB version from browser :
/usr/lib/lua/luci/dispatcher.lua:448: Failed to execute function dispatcher target for entry '/admin/system'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:448: Failed to execute cbi dispatcher target for entry '/admin/system/system'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:104: Failed to execute template 'cbi/header'.
A runtime error occured: /usr/lib/lua/luci/template.lua:104: Failed to execute template 'header'.
A runtime error occured: /usr/lib/lua/luci/template.lua:104: Failed to execute template 'themes/material/header'.
A runtime error occured: [string "/usr/lib/lua/luci/view/themes/material/head..."]:7: attempt to call field 'ubus' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:448: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:195: in function </usr/lib/lua/luci/dispatcher.lua:194>

**Comment by LuttyYang** [comment]
BB is deprecated, as CC 15.05 has been released...

The post-installation script handling was changed between BB and CC, so the .ipk fails with BB. But it should be compatible with CC although it has been built for trunk.

Creating a separate BB .ipk build would require the author to have a separate Openwrt toolchain for BB that should be used for the compilation.
