### ISSUE TITLE
//usr/lib/opkg/info/luci-theme-material.postinst: line 4: default_postinst: not found

### ISSUE THREAD

**Issue by youlunzhai12** [LuttyYang/luci-theme-material#21]
[root@PandoraBox:/root]#opkg install /tmp/luci-theme-material_0.2.15-1_all.ipk
Installing luci-theme-material (0.2.15-1) to root...
Configuring luci-theme-material.
//usr/lib/opkg/info/luci-theme-material.postinst: line 4: default_postinst: not found
Collected errors:
 * pkg_run_script: package "luci-theme-material" postinst script returned status 127.
 * opkg_configure: luci-theme-material.postinst returned 127.

**Comment by LuttyYang** [comment]
PB is deprecated, as CC 15.05 has been released...

The post-installation script handling was changed between PB and CC, so the .ipk fails with PB. But it should be compatible with CC although it has been built for trunk.
