### ISSUE TITLE
Failed to execute template 'sysauth'.

### ISSUE THREAD

**Issue by tobor** [LuttyYang/luci-theme-material#22]
Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
Failed to execute template 'sysauth'.
A runtime error occured: Failed to execute template 'header'.
A runtime error occured: Failed to execute template 'themes/material/header'.
A runtime error occured: [string "/usr/lib/lua/luci/view/themes/material/head..."]:8: attempt to call field 'ubus' (a nil value)
stack traceback:
	[C]: in function 'assert'
	?: in function 'dispatch'
	?: in function <?:194>

**Comment by LuttyYang** [comment]
this theme is work on CC 15.05.
