### ISSUE TITLE
support for 3rd radio (radio2)

### ISSUE THREAD

**Issue by tca22** [LuttyYang/luci-theme-material#24]
Hello,
I am using the theme on a Meraki18 and it seems the 3rd radio is not supported.
It is however displayed on the "Wifi Overview" page, but whenever I want to 'edit' the 3rd radio (radio2) it shows:

"Bad Gateway
The process did not produce any response"

I would assume radio2 is not supported - or is there a tweak which I should apply?

Thanks,
Tom

**Comment by LuttyYang** [comment]
I am very sorry to hear this. But I don't think this is theme's problem. 

I think you can try change the theme, If this problem already exists, you can post a issue to LUCI project.

Thanks

**Comment by LuttyYang** [comment]
If this is theme's problem, please tell me, thanks

**Comment by tca22** [comment]
Ok, Thanks!

btw. great theme, thanks for the work :-)
