### ISSUE TITLE
LED Configuration page delete buttons

### ISSUE THREAD

**Issue by shunjou** [LuttyYang/luci-theme-material#26]
The delete buttons on the led configuration page appear orphaned from their respective rules due to the alternating background color applied.

Changing the selector `.cbi-section-remove:nth-of-type(2n)` to `.cbi-section-remove:nth-of-type(2n+1)` on line 676 in style.css seems to fix it.

**Comment by LuttyYang** [comment]
thanks

**Comment by LuttyYang** [comment]
Thank you for your feedback, but I did not find this problem on the my router (WNDR3800).

![screenshot from 2016-03-30 12-22-16](https://cloud.githubusercontent.com/assets/14296262/14131898/25c867dc-f672-11e5-84e0-8e221988678a.png)

**Comment by shunjou** [comment]
This is what I see on my TP-Link Archer C7 running 15.05.1 with the theme installed from the 0.2.17 release ipk. It matches yours with the mentioned css change.

![c7_led_config](https://cloud.githubusercontent.com/assets/16366798/14155026/d820ad2a-f68d-11e5-8817-118a5f36c433.png)

**Comment by shunjou** [comment]
To follow up, I no longer experience this issue after updating luci from git-16.081.39589-0207cb7-1 to git-16.164.65694-cd50f27-1 so it must have only occurred with older luci versions not in trunk.

There are other issues using a newer luci, such as the host column in wireless display having an unnecessary 200px max-width causing it to be off center as well as various margin and spacing errors especially on mobile, but otherwise the theme is very good.
