### ISSUE TITLE
Failed To Load

### ISSUE THREAD

**Issue by HendyElectrician** [LuttyYang/luci-theme-material#27]
Please help, unable to load theme

/usr/lib/lua/luci/dispatcher.lua:448: Failed to execute template dispatcher target for entry '/admin/status/overview'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:120: Failed to execute template 'admin_status/index'.
A runtime error occured: /usr/lib/lua/luci/template.lua:120: Failed to execute template 'header'.
A runtime error occured: /usr/lib/lua/luci/template.lua:120: Failed to execute template 'themes/material/header'.
A runtime error occured: [string "/usr/lib/lua/luci/view/themes/material/head..."]:8: attempt to call field 'ubus' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:448: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:195: in function </usr/lib/lua/luci/dispatcher.lua:194>

**Comment by LuttyYang** [comment]
Please give me your openwrt version, thanks

**Comment by jsalonl** [comment]
Great Job and beautiful design but Same error
My OpenWRT is  ATTITUDE ADJUSTMENT (12.09-beta, r33312).

Please help !

**Comment by LuttyYang** [comment]
@jsalonl 12.09 is old and deprecated, as CC 15.05 has been released...

This theme is only test in CC，you can flash the newest rom in your router and enjoy this theme!

Thank you for your support! :)
