### ISSUE TITLE
Too large font in fixed-width text areas decreases usability

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#3]
I don't usually browse with a full width 1920 pixel window, instead I like something like 1200 px wide browser window and the comment below reflects that.

Material has a wide left menu and uses a rather large font size for the "fixed-width text" areas that are used for log display and also for entering SSH keys, opkg config etc. "text file" stuff. That was also pointed out in the forum discussion: https://forum.openwrt.org/viewtopic.php?pid=292310#p292310

You might consider decreasing the font size a bit on those text areas. At least in cases, when the display width is not the full 1920+

Below is example how Material shows much less actual content than Bootstrap. Most of the useful info gets pushed right.

![largetextfont](https://cloud.githubusercontent.com/assets/7926856/9953658/48ea4f3e-5deb-11e5-9f9a-6b3c946b4061.PNG)

In the second example, the lines in opkg feed config have been wrapped in Material, while fitting to one row in Bootstrap. 
(Side note: I will check the luci code to see if a config item needs to be added to prevent wrapping there, as e.g. the SSH key input does not word-wrap. EDIT: I pushed a fix to Luci to prevent word-wrap on those opkg config fields. )

![large2](https://cloud.githubusercontent.com/assets/7926856/9953769/6be6e76c-5dec-11e5-9f2d-e36f423b96ee.PNG)

**Comment by hnyman** [comment]
Ps. I noticed that your commit https://github.com/LuttyYang/luci/commit/2237aab76b6876bc9bc1c0c0fad818898cfbe495 in your "uplift to Openwrt luci" repo contains also your gitconfig file. https://github.com/LuttyYang/luci/commit/2237aab76b6876bc9bc1c0c0fad818898cfbe495#diff-6cb0f77b38346e0fed47293bdc6430c6

You need to naturally remove that before creating any pull request.

**Comment by hnyman** [comment]
Actually, Bootstrap does not use fixed-width font for those areas, I just noticed. That makes text to fit better.

**Comment by LuttyYang** [comment]
@hnyman  thanks a lot, I fix them on version 0.1.4

I use font-size: smaller  when the display width is not the full 1600, smaller are different sizes in different browsers, It's up to you browser setting

![screenshot from 2015-09-18 15 47 15](https://cloud.githubusercontent.com/assets/14296262/9955087/cea11592-5e20-11e5-855c-446f6dae82c8.png)

**Comment by hnyman** [comment]
Looks better now.
