### ISSUE TITLE
IPv4 WAN Status is not Correct

### ISSUE THREAD

**Issue by hzxie** [LuttyYang/luci-theme-material#30]
![screenshot from 2016-07-05 09 10 16](https://cloud.githubusercontent.com/assets/1730504/16571520/7ac2df14-4290-11e6-996b-502c4a8b19d0.png)

As the figure shown above, the IPv4 WAN Status is `192.168.113.1`. Actually, the IP should be `202.118.228.69`. It seems there's something wrong with getting information of IPv4.

**Comment by zjhzxhz** [comment]
Here's the correct information.

![screenshot from 2016-07-05 09 13 31](https://cloud.githubusercontent.com/assets/1730504/16571533/c66dd752-4290-11e6-8834-f28dbe840f48.png)

**Comment by LuttyYang** [comment]
I am very sorry to hear this. But I don't think this is the theme problem.

I think you can try change the theme, If this problem already exists, you can post a issue to LUCI project.

Thanks

LUCI project url: https://github.com/openwrt/luci
