### ISSUE TITLE
how can i install this theme

### ISSUE THREAD

**Issue by palat** [LuttyYang/luci-theme-material#31]
please help guide me to install this theme

**Comment by streetonice** [comment]
https://forum.openwrt.org/viewtopic.php?id=59696
easy to do

**Comment by stasink** [comment]
Required packages: wget, curl, ca-certificates

mkdir tmp
cd tmp
wget https://github.com/LuttyYang/luci-theme-material/releases/download/v0.2.17/luci-theme-material_0.2.17-1_all.ipk
opkg install luci-theme-material_0.2.17-1_all.ipk

You can switch the theme under System > System > Language and Style.

Enjoy!
