### ISSUE TITLE
http://192.168.1.1/cgi-bin/luci/;stok=540bf6c0e6e7a53898ee5e5d10094000/admin/status/iptables

### ISSUE THREAD

**Issue by joonkui95** [LuttyYang/luci-theme-material#32]
unlimited loop

**Comment by LuttyYang** [comment]
I can not reproduce the bug

**Comment by AdrianoCahete** [comment]
Same here, but at login page. Clean install, installed this theme and then i cannot login.

When package is uninstaled via ssh/telnet, the admin dashboard loading again.
