### ISSUE TITLE
links not adding / before the paths

### ISSUE THREAD

**Issue by dman776** [LuttyYang/luci-theme-material#33]
none of links are being built correctly with this theme. (Chaos Calmer)

I always end up with links like this:
http://myhost:8080/cgi-bin/luci/;stok=bf5a3a223d058a2bf25499461fdc9599admin/status/overview
instead of 
http://myhost:8080/cgi-bin/luci/;stok=bf5a3a223d058a2bf25499461fdc95/admin/status/overview

**Comment by dman776** [comment]
Is anyone else seeing this behavior, or, is it just me?

**Comment by LuttyYang** [comment]
Please upgrade the firmware to the latest version
