### ISSUE TITLE
How to apply this theme after installation

### ISSUE THREAD

**Issue by jkng** [LuttyYang/luci-theme-material#34]
![qq 20170120034804](https://cloud.githubusercontent.com/assets/12867321/22122566/6b565a2c-dec3-11e6-9e3b-8f9f18e3fa43.png)
How to apply this theme in putty

**Comment by jkng** [comment]
The router does not select an item for the topic

**Comment by LuttyYang** [comment]
You can switch the theme under System > System > Language and Style.
