### ISSUE TITLE
BUG: Incorrect URL for "Unsaved Changes" button in header.htm, extra //.

### ISSUE THREAD

**Issue by NvrBst** [LuttyYang/luci-theme-material#35]
When you click the "Unsaved Changes" button, it puts and extra "//" between luci and admin, as shown below:

`192.168.0.1/cgi-bin/luci//admin/uci/changes?redir=%2fcgi-bin%2fluci%2fadmin%2fnetwork%2fdhcp`

The code in _header.htm_ is below. removing the "/" between controller and category does work, but not too sure if thats the correct way to do it:
`Line 164: <a class="label notice" href="<%=controller%>/<%=category%>/uci/changes?redir=<%=http.urlencode(http.formvalue("redir") or REQUEST_URI)%>"><span class="mobile-hide"><%:Unsaved Changes%>: </span><%=ucichanges%></a>`

The latest bootstrap theme did what u did. But now moved the button into a function called "render_changes()":

```
HTML just called Button function: <% render_changes() %>
Code for render_changed():
				write('<a class="label notice" href="%s?redir=%s">%s: %d</a>' %{
					url(category, 'uci/changes'),
					http.urlencode(http.formvalue('redir') or REQUEST_URI),
					translate('Unsaved Changes'),
					ucichanges
```

Maybe nit picking, but easy fix, and won't have any more malformed URL in the theme.

**Comment by LuttyYang** [comment]
thanks, I fixed this issue
