### ISSUE TITLE
switch tab cannot show port status

### ISSUE THREAD

**Issue by harrylwc** [LuttyYang/luci-theme-material#36]

**Comment by 1hub** [comment]
Marked part is missing in Material theme (Network / Switch menu item):
![luci-switch-bootstrap-marked](https://cloud.githubusercontent.com/assets/20463482/24072140/4dba6a52-0be2-11e7-889c-d1124028cca2.PNG)
(picture from Bootstrap theme)

**Comment by harrylwc** [comment]
find the solution here
https://github.com/openwrt-develop/luci-theme-atmaterial

**Comment by 1hub** [comment]
ATMaterial is a different theme and I don't like it. Is it possible to copy certain files only to Material theme to show port status and preserve original Material theme look?

**Comment by harrylwc** [comment]
from source code here
https://github.com/openwrt-develop/luci-theme-atmaterial/commit/7806d4f4da3f080c2144872af6b069569ca6395b
It may only need to modify the .js code 

files/htdocs/js/script.js

**Comment by 1hub** [comment]
Yes, you are right, modified .js file solved it, thank you. I thought it was a bug in the theme but someone intentionally added 6 lines of code to hide this useful info. I don't get why.
