### ISSUE TITLE
Gap between </ul> and <div> in tabbed maps

### ISSUE THREAD

**Issue by stangri** [LuttyYang/luci-theme-material#37]
This theme seems to have a bug with tabbed maps (```m.tabbed = true```) as evidenced by the screenshot. This gap between tabs and their content is not present in the bootstrap theme and as a workaround I've used the modified map template (line 13: ```<ul class="cbi-tabmenu map" style="margin-bottom:-32px;">``` and removed the ```<br />```) which is an ugly fix.
![screen shot 2017-03-08 at 13 30 42](https://cloud.githubusercontent.com/assets/4768176/23725026/d1f1405c-0403-11e7-927a-6ab67da4b0da.png)

I do not have enough HTML5/CSS skills to hunt down the bug tho, hopefully someone more knowledgeable will.

**Comment by LuttyYang** [comment]
I don't known where this page is, please tell me where can find this page~

**Comment by stangri** [comment]
This screenshot is from `luci-app-openvpn-policy-routing`. I have now used a custom map file which fixes a bug in your theme. If you want to reproduce the bug, install `luci-app-openvpn-policy-routing` from https://stangri.github.io/openwrt-repo/ and change line 78 of `/usr/lib/lua/luci/model/cbi/openvpn-policy-routing.lua` file to:
`p.template="cbi/map"
`
