### ISSUE TITLE
Cannot satisfy the following dependencies for luci-theme-material

### ISSUE THREAD

**Issue by gegtor** [LuttyYang/luci-theme-material#38]
I when i try do install theme using 

opkg install ./luci-theme-material_0.2.18-1_all.ipk 

i get

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-theme-material:
 * 	libssp * 
 * opkg_install_cmd: Cannot install package luci-theme-material.

Error :(

**Comment by LuttyYang** [comment]
Please tell me your openwrt and luci version, thanks

**Comment by onexay** [comment]
Same issue.

root@OpenWrt:/tmp# opkg install /tmp/luci-theme-material_0.2.18-1_all.ipk 
Installing luci-theme-material (0.2.18-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-theme-material:
 * 	libssp * 	librt * 
 * opkg_install_cmd: Cannot install package luci-theme-material.

BusyBox v1.25.1 () built-in shell (ash)

     _________
    /        /\      _    ___ ___  ___
   /  LE    /  \    | |  | __|   \| __|
  /    DE  /    \   | |__| _|| |) | _|
 /________/  LE  \  |____|___|___/|___|                      lede-project.org
 \        \   DE /
  \    LE  \    /  -----------------------------------------------------------
   \  DE    \  /    Reboot (17.01.1, r3316-7eb58cf109)
    \________\/    -----------------------------------------------------------

root@OpenWrt:~# 

LuCI git-17.126.47277-596f476-1

**Comment by KiPiCoOl** [comment]
Same issue 

OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-188-g87e9837 Release (git-16.043.44305-e2f9172)

**Comment by alexsalex** [comment]
Same issue
Powered by LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55) / OpenWrt Chaos Calmer 15.05.1

**Comment by Ryuzakix3** [comment]
Same issue

Powered by LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55)

**Comment by AveyBD** [comment]
**Same Issue.** 
root@OpenWrt:/tmp# opkg install luci-theme-material_0.2.18-1_all.ipk 
Installing luci-theme-material (0.2.18-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-theme-material:
 * 	libssp * 	librt * 	libpthread * 
 * opkg_install_cmd: Cannot install package luci-theme-material.

**Comment by gegtor** [comment]
I just used previous release and it worked fine

**Comment by Cereal-Killa** [comment]
I used "--force-depends" and it worked alright: opkg install ./luci-theme-material*.ipk --force-depends

I would be nice though to fix that issue so it can be installed normally.

Running LEDE Reboot 17.01.2 r3435-65eec8bd5f / LuCI lede-17.01 branch (git-17.152.82987-7f6fc16)

**Comment by Justin417** [comment]
Can confirm @Cereal-Killa's method works. 
Running `opkg install ./luci-theme-material*.ipk --force-depends` still throws the error, but the package is installed normally.

Running LEDE Reboot (17.01.2, r3435-65eec8bd5f) on a WD MyNet Range Extender.

**Comment by alexsalex** [comment]
after `opkg install ./luci-theme-material*.ipk --force-depends` login stuck on 

> Loading

**Comment by LuttyYang** [comment]
I fix it issue in version 0.2.19, thanks
