### ISSUE TITLE
Version info is not visible in footer

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#4]
I find it useful that the footer with detailed version info is visible on every page. Bootstrap has this footer:

    Powered by LuCI (git-15.258.28302-30f6fe8) / OpenWrt Chaos Calmer 15.05-r46989 

That is useful especially when you have several routers to which you constantly flash new firmware versions. Or when reporting bugs.

I don't really care where it is visible, as long as it is visible and text is selectable with mouse. So, it might be located 
* in the bottom as a footer, like in Bootstrap
* in the bottom of the left menu bar if it wraps nicely. E.g. two lines: Openwrt version info and Luci version info
* or at the top row after the router name.

**Comment by LuttyYang** [comment]
@hnyman I add it on version 0.2

in version 0.2 I add a loading animation, You feeling okay with this experimental features？
