### ISSUE TITLE
Failed to execute template 'themes/material/header'. attempt to call global 'url' (a nil value)

### ISSUE THREAD

**Issue by figoym** [LuttyYang/luci-theme-material#40]
Mon Jun 12 21:44:31 2017 daemon.err uhttpd[844]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/material/header'.
Mon Jun 12 21:44:31 2017 daemon.err uhttpd[844]: A runtime error occured: [string "/usr/lib/lua/luci/view/themes/material/head..."]:37: attempt to call global 'url' (a nil value)
Mon Jun 12 21:44:31 2017 daemon.err uhttpd[844]: stack traceback:
Mon Jun 12 21:44:31 2017 daemon.err uhttpd[844]:        [C]: in function 'assert'
Mon Jun 12 21:44:31 2017 daemon.err uhttpd[844]:        /usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
Mon Jun 12 21:44:31 2017 daemon.err uhttpd[844]:        /usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>

**Comment by figoym** [comment]
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio (double int32)

**Comment by figoym** [comment]
Openwrt 15.05 , Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio (double int32)

**Comment by figoym** [comment]
version=0.2.18, no this issue in version 0.2.17

**Comment by LuttyYang** [comment]
I only test 0.2.18 in LUCI version git-17.109.24760-2eda14bee, sorry about that
