### ISSUE TITLE
ipk build for BB

### ISSUE THREAD

**Issue by rufik** [LuttyYang/luci-theme-material#5]
Is it possible to get built for BB? Installing ipk right now results in error:
`Installing luci-theme-material (git-15.259.53707-f3f0de3-1) to root...`
`Configuring luci-theme-material.`
`//usr/lib/opkg/info/luci-theme-material.postinst: line 4: default_postinst: not found`
`Collected errors:`
` * pkg_run_script: package "luci-theme-material" postinst script returned status 127.`
` * opkg_configure: luci-theme-material.postinst returned 127.`

**Comment by hnyman** [comment]
BB is deprecated, as CC 15.05 has been released...

The post-installation script handling was changed between BB and CC, so the .ipk fails with BB. But it should be compatible with CC although it has been built for trunk.

Creating a separate BB .ipk build would require the author to have a separate Openwrt toolchain for BB that should be used for the compilation.

**Comment by LuttyYang** [comment]
@rufik I build a ipk for BB, but I did not test it, please be careful when you use it..

download url: http://goo.gl/9baZSP

**Comment by rufik** [comment]
@LuttyYang No go, exactly the same issue :/

**Comment by LuttyYang** [comment]
@rufik  maybe I misplaced, you can try it:

http://goo.gl/0NQtz0

**Comment by rufik** [comment]
Thanks a lot, installation went sucessfully, but I got fatal error:

Failed to execute template dispatcher target for entry '/admin/status/overview'.
The called action terminated with an exception:
Failed to execute template 'admin_status/index'.
A runtime error occured: Failed to execute template 'header'.
A runtime error occured: Failed to execute template 'themes/material/header'.
A runtime error occured: [string "/usr/lib/lua/luci/view/themes/material/head..."]:7: attempt to call field 'ubus' (a nil value)
stack traceback:
	[C]: in function 'assert'
	?: in function 'dispatch'
	?: in function <?:194>

So the issue is bigger and I think there is no sense backporting it to BB.

**Comment by hnyman** [comment]
You are probably right, as there was a massive Luci build system reorganisation after BB14.07 (luci-0.12) was branched: https://github.com/openwrt/luci/commit/1bb4822dca6113f73e3bc89e2acf15935e6f8e92. That caused additional fixes for themes in January 2015 as can be seen from "bootstrap" in the for-15.05 branch: https://github.com/openwrt/luci/commits/for-15.05/themes/luci-theme-bootstrap

It would be a waste of effort to make all the changes needed for backporting the new theme to the already retired BB14.07.
