### ISSUE TITLE
System log and kernel log do not set focus correctly to immediately scroll with keyboard

### ISSUE THREAD

**Issue by hnyman** [LuttyYang/luci-theme-material#6]
System log and kernel log do not scroll nicely with keyboard. 

In bootstrap, if you enter the system log or kernel log page, you can immediately use keyboard PageDown or PageUp keys to scroll the log by one text screen at the time.

In Material, the focus does not switch from menu to the log page, so nothing happens with the keys. You have to click the log page area to focus the keyboard actions to cause scrolling.

(Both themes have the annoying feature that if you click on the log text itself, the PageDn and PageUp keys scroll either to the top or bottom of the text. You have to click the page area outside the log textbox to get proper "scroll one screen at time" functionality.)

**Comment by LuttyYang** [comment]
@hnyman I fixed it on version 0.2.2
