### ISSUE TITLE
SQM QoS tab layout issue

### ISSUE THREAD

**Issue by zp** [LuttyYang/luci-theme-material#7]
Version 0.2.2

The Queue Discipline tab in SQM QoS (from luci-app-sqm) has a small layout issue

![luci-theme-material](http://i.imgur.com/FIBa8ct.png)

Default bootstrap theme for comparison

![luci-theme-bootstrap](http://i.imgur.com/d0sIGnx.png)

The other SQM QoS tabs appear to be fine.

**Comment by LuttyYang** [comment]
I fix it in version 0.2.3
